spring:
  data:
    mongodb:
      uri: mongodb://tomwodz:tomwodz@localhost:27017/mongo_lottogame
      config:
        enabled: true
        write:
          writeConcern:
            isMajority: true
          timeout:
            milliseconds: 30000
  main:
    allow-bean-definition-overriding: true

lotto-game:
  number-client:
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 2000
          readTimeout: 2000
  number-generator:
    criteria:
      count: 6
      lowerBand: 1
      upperBand: 99
      countOut: 25
    lotteryRunOccurrence: "0 0 12 * * 6"
  result-checker:
    lotteryRunOccurrence: "0 55 11 * * 6"